# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Writing Guide
tagline:          'How to talk to our customers'
description:      'A guide to making our customers happy by using the right words at the right times.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Nat Dudley'
  url:            https://twitter.com/natdudley

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
